### ISSUE TITLE
SPIKE: explore the options for reducing / cutting video to improve unstable

### ISSUE THREAD

**Issue by ebporter** [rifflearning/zenhub#16]
In order to improve the user's experience of using the Riff video chat, this spike will look at options for putting up messaging for users when one or more of the peer connections become unstable and the video (or audio) feed can't be shown.

** Spike acceptance criteria **

A written document that includes the following information:

- [ ] The scope and sequence of work to detect degraded connections, that impact the ability of users to communicate effectively, specifically, broken audio and frozen video. 
- [ ] The scope and sequence of work to automatically shut off video in order to use available bandwidth to improve the audio quality. 
- [ ] The scope and sequence of work to poll the signal for a high-enough, stable threshold to sustain video, and re-establish the video connection. 
- [ ] The scope and sequence of work to message the user about the experience above. 
- [ ] The viability of implementing, testing and deploying this work in time for fall NEXT course run (9/17).

**Comment by adonahue** [comment]
Accepting this story as complete, based on @jordanreedie prototype implementation of bandwidth limiting in DEV.
